name: CI/CD

on:
  push:
    branches: [ feature/final_task ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Format check
        run: |
          pip install black isort
          black --check .
          isort --check-only .

      - name: Run Lint (flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        env:
          SECRET_KEY: test-secret-key
          DEBUG: "False"
          DATABASE_NAME: test_db
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          python manage.py migrate
          pytest -v

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker compose build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            cd /home/ilya/lms_project

            git pull origin feature/ci_cd

            docker compose down
            docker compose up -d --build

            # безопасный прогрев (важно для Django)
            docker compose exec -T web python manage.py migrate
            docker compose exec -T web python manage.py collectstatic --noinput